PyCQA/flake8

- flake8/hooks.py
- flake8/tests/test_git_hook.py
The git hook wasn't handling exclude patterns correctly. These two commits fix that problem and add unit tests to demonstrate it.
> Correctly handle exclude patterns in git_hook (now with unit tests)

- CHANGES.rst
- README.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- src/flake8/main/application.py
- tests/unit/test_application.py
`Application.parse_preliminary_options_and_args` was previously, against
expectations, treating empty lists passed as the `argv` argument the
same way it treated `None`s.
This has been addressed and the correct behavior tested for in a unit
test of the `Application` class.
See issue #518 for details.
> Fixes handling of empty lists by Application

- docs/source/user/invocation.rst
- docs/source/user/options.rst
- src/flake8/main/options.py
- src/flake8/style_guide.py
- tests/unit/test_decision_engine.py
- tests/unit/test_style_guide.py
Implement `--extend-select` command line argument following what was
done for `--extend-ignore` in !233 (see placeholder issue #1274). This option can be used to
selectively add individual codes without overriding the default list
entirely.
Addresses the remaining item of issue #1061.
> Add --extend-select command line argument

- src/flake8/options/aggregator.py
- src/flake8/style_guide.py
- tests/unit/test_decision_engine.py
- tests/unit/test_style_guide.py
Since Flake8 3.0 we've had the ability for plugins to use
`extend_default_ignore` to register codes they want disabled by default.
This, however, was a permanent disabling unfortunately. Our code didn't
have a way of understanding that this new set of `ignore` codes was
actually the 'default' set for that run. Much like the
extended_select_list, we now attach extended_ignore_list to be able to
confidently determine if the ignore we get in the DecisionEngine is
actually the Default Ignore list and what plugins what us to ignore by
default.
Refs https://github.com/PyCQA/pep8-naming/pull/157
--- 
Extra entertainment for Anthony
> Fix bug for plugins using extend_default_ignore

- src/flake8/formatting/base.py
- tests/integration/test_main.py
If the output file is on a non-existing path, we should create the missing components, just like is done in the handling of `--junit-xml=` in `pytest`.
> Automatically create output directories

- docs/source/user/using-plugins.rst
Replaces `flake8-future` with `flake8-quotes`
Why?
I was reading through the docs and I saw an interesting plugin which I was not aware of.
That's what I saw:
This is clearly an outdated example, I have switched it to a more modern one.
> Improves plugin docs

- src/flake8/main/options.py
Fixes this warning:
```
WARNING  flake8.options.manager:manager.py:186 option --indent-size: please update `help=` text to use %(default)s instead of %default -- this will be an error in the future
```
> Update --indent-size help format string

- src/flake8/checker.py
- tests/integration/test_checker.py
> Handle new SyntaxError tuple on 3.10

- src/flake8/formatting/base.py
- tests/unit/test_base_formatter.py
> write directly to sys.stdout.buffer to avoid windows io encoding

- docs/source/requirements.txt
docutils 0.18 is busted and needs to be prevented from being installed
Related to https://github.com/sphinx-doc/sphinx/issues/9788
Related to https://github.com/readthedocs/readthedocs.org/issues/8616
> Fix ReadTheDocs builds

- docs/source/user/options.rst
- src/flake8/main/application.py
- src/flake8/main/options.py
> deprecate the --diff option

- docs/source/manpage.rst
- docs/source/user/invocation.rst
- docs/source/user/options.rst
- src/flake8/defaults.py
I think this is everywhere that it should be added to, docs and `defaults.py`.
Closes #1442
> Add .nox to default exclude list

- .coveragerc
- tox.ini
coverage 6.x has smarter `paths` discovery so we no longer need our custom config
> require coverage 6.x and simplify config

- src/flake8/options/config.py
- tests/integration/test_main.py
- tests/unit/test_options_config.py
> return an error if the explicitly specified config is missing

- src/flake8/checker.py
originally failing with:
```
Warning, treated as error:
/tmp/flake8/.tox/docs/lib/python3.8/site-packages/flake8/checker.py:docstring of flake8.checker.Manager.run:6:hardcoded link 'https://github.com/pycqa/flake8/issues/117' could be replaced by an extlink (try using ':issue:`117`' instead)
```
> fix docs build

- docs/source/internal/checker.rst
- src/flake8/__init__.py
- src/flake8/checker.py
- src/flake8/processor.py
- tests/unit/conftest.py
- tests/unit/test_file_processor.py
- flake8 spent 5% of execution in `log_token`
- `EXTRA_VERBOSE` was only used by `log_token`
- `python -m tokenize` provides better debug token output
> remove `log_token` and `EXTRA_VERBOSE`

- src/flake8/checker.py
- src/flake8/processor.py
when run with `flake8 -v` the stacktrace for this error was getting logged thrice
> remove triple logged stacktrace on unknown plugin args

- src/flake8/checker.py
flake8 spends ~5-6% of `flake8 -j1 src` on this line
___
personally I don't use any of the `debug(...)` logging information and prefer to use `pdb` myself.  I wouldn't be opposed to removing the rest of the debug lines as well -- though this one appears to be the most performance impacting one (even at the default log level)
> remove slow debug() log

- src/flake8/options/aggregator.py
- src/flake8/options/manager.py
- tests/integration/test_plugins.py
- tests/unit/test_option_manager.py
for #1550 
I think this is worth doing anyway -- though we should reconsider whether showing the configured values as "default" in `--help` is desirable or not
> make --ignore order consistent

- src/flake8/main/options.py
- src/flake8/options/aggregator.py
- src/flake8/style_guide.py
- tests/integration/test_aggregator.py
- tests/unit/test_decision_engine.py
- not specified codes (cmdline / config) are now known as being implicit via
None sentinel
- removed redundant logic for (explicit, explicit) selection
resolves #284
> simplify decision engine

- src/flake8/style_guide.py
We are always returning the last element so a 'max' operation is sufficient instead of sorting. Note the old code did not handle an empty list so this change doesn't either
> Remove needless sort in `_style_guide_for`

- src/flake8/plugins/finder.py
- tests/unit/plugins/finder_test.py
for example, `venv`-virtualenvs on fedora have both `lib` and `lib64` on
`sys.path` despite them being the same.  this causes
`importlib.metadata.distributions` to double-discover.
```console
$ docker run --rm -t fedora:latest bash -c 'dnf install -qq -y python3 >& /dev/null && python3 -m venv venv && venv/bin/pip -qq install cfgv && venv/bin/python - <<< "from importlib.metadata import distributions; print(len([d for d in distributions() if d.name == '"'"'cfgv'"'"']))"'
2
```
resolves #1627
> prevent duplicate plugin discovery on misconfigured pythons

- src/flake8/options/config.py
- tests/unit/test_options_config.py
> skip skipping home if home does not exist

- src/flake8/options/config.py
- tests/unit/test_options_config.py
> ignore config files that partially parse as flake8 configs

- docs/source/plugin-development/registering-plugins.rst
Clarified what is and is not a valid entry point name
for registering plugins.
> Clarify entry point naming

- docs/source/user/options.rst
This PR fixes https://github.com/PyCQA/flake8/issues/1661 , where the `color` option was not being picked up from the config file, which I assumed was a bug since the documentation suggests it should be configurable from there: https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-color
> fix documentation of color configuruation

- docs/source/plugin-development/registering-plugins.rst
Hey, I found a small typo in the docs and here is a simple PR to fix it
> Fix typo casae->case

- docs/source/index.rst
- docs/source/user/configuration.rst
See #1679
I changed the error codes in `index.rst` so they weren't ones that are disabled by default.
I changed the error code in `configuration.rst` as `E203` is what is actually ignored by flake8 now: https://github.com/PyCQA/flake8/blob/4d1a72afc2825480b0d562a2c13c3a94c923a174/tox.ini#L121
> Prefer extend-ignore over ignore in general examples

- src/flake8/main/options.py
It erroneously claimed that it set the application exit code to 1 if the count was greater than 1. However, this is false, because the --count option doesn't modify the error code at any time.
If the count was greater than 1, then the exit code was already 1, even in the absence of --count, unless --exit-zero was used.
This documentation bug resulted in people reading the `flake8 --help` output and believing that --count is mandatory in order to ensure that flake8 produces errors in automated processes (such as CI scripts) when flake8 violations are detected.
> fix documentation for the --count option

- .github/FUNDING.yml
resolves #1700 
`@sigmavirus24` is unable to be sponsored due to work, but I'll throw mine in there
if we decide on adding tidelift -- there's also a field for tidelift here as well [for example](https://github.com/pytest-dev/pytest/blob/2be1b8f3559570c456f4bf64fea8067e368dcdfd/.github/FUNDING.yml#L4)
> Add link to GitHub Sponsors for primary maintainer

- src/flake8/main/application.py
- src/flake8/main/options.py
- src/flake8/options/manager.py
- tests/integration/test_aggregator.py
- tests/integration/test_main.py
- tests/integration/test_plugins.py
- tests/unit/test_option_manager.py
- tests/unit/test_options_config.py
> Display list of available formatters with help for `--format`

- src/flake8/defaults.py
- src/flake8/options/config.py
- src/flake8/plugins/finder.py
- tests/unit/plugins/finder_test.py
- tests/unit/test_defaults.py
- tests/unit/test_options_config.py
This PR resolves #1689 by raising a warning when parsing a configuration file results in values for the --ignore or --extend-ignore options that cannot be valid error codes, i.e. they are not in a 'A123' format.
> Adds error when incorrect error codes are parsed from config file

- src/flake8/options/config.py
- tests/unit/test_options_config.py
This PR resolves https://github.com/PyCQA/flake8/issues/1729 by raising  a exception if append-config files does not exist
> Raise a exception if append-config files does not exist

- src/flake8/options/manager.py
- tests/unit/test_option_manager.py
been deprecated for 2+ years, time to remove it -- should make reworking this easier
___
here's the error messages that you'll see as well as how to fix things:
error:
```console
$ flake8 --help
...
File "/usr/lib/python3.10/argparse.py", line 642, in _expand_help
return self._get_help_string(action) % params
TypeError: %d format: a real number is required, not dict
```
error:
```console
$ flake8 t.py
...
File "/home/asottile/workspace/flake8/a.py", line 7, in add_options
parser.add_option(
File "/home/asottile/workspace/flake8/src/flake8/options/manager.py", line 278, in add_option
option = Option(*args, **kwargs)
TypeError: Option.__init__() got an unexpected keyword argument 'callback'
```
```console
$ flake8 t.py
...
File "/home/asottile/workspace/flake8/a.py", line 7, in add_options …
```
> remove optparse support

- src/flake8/processor.py
- tests/integration/test_plugins.py
this is new in 3.12 -- the tests don't yet pass due to pyflakes and pycodestyle.  but at least this new test passes:
```console
$ ./venv312/bin/pytest tests/integration/test_plugins.py --show-capture=no
============================= test session starts ==============================
platform linux -- Python 3.12.0b2+, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/asottile/workspace/flake8
configfile: pytest.ini
collected 6 items                                                              
tests/integration/test_plugins.py ......                                 [100%]
============================== 6 passed in 0.17s ===============================
```
> mute FSTRING_MIDDLE tokens

- docs/source/conf.py
- docs/source/requirements.txt
The sphinx-prompt plugin has renamed its package in 1.8.0 from erraneous `sphinx-prompt` name to `sphinx_prompt`.  Adjust the conf accordingly.
> update plugins for sphinx-prompt-1.8.0

- docs/source/plugin-development/registering-plugins.rst
Seems like I messed up in https://github.com/PyCQA/flake8/pull/1923
> Fix wording of plugins documentation

- src/flake8/processor.py
- tests/integration/test_plugins.py
To use a curly brace in an f-string, you must escape it. For example:
```python
>>> k = 1
>>> f'{{{k}'
'{1'
```
Saving this as a script and running the 'tokenize' module highlights something odd around the counting of tokens:
```console
$ python -m tokenize test.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,1:            NAME           'k'
1,2-1,3:            OP             '='
1,4-1,5:            NUMBER         '1'
1,5-1,6:            NEWLINE        '\n'
2,0-2,2:            FSTRING_START  "f'"
2,2-2,3:            FSTRING_MIDDLE '{'     # <-- here...
2,4-2,5:            OP             '{'     # <-- and here
2,5-2,6:            NAME           'k'
2,6-2,7:            OP             '}'
2,7-2,8:            FSTRING_END    "'"
2,8-2,9:            NEWLINE        '\n'
3,0-3,0: …
```
> Handle escaped braces in f-strings
