PyCQA/flake8

docs/config.rst

Per Code Line

---

CONTRIBUTORS.txt

I pushed last year
(https://github.com/PyCQA/flake8/pull/2#issuecomment-77674012) and
forgot to add myself.

Adding myself to CONTRIBUTORS.txt

---

src/flake8/checker.py
src/flake8/exceptions.py
src/flake8/processor.py
tests/integration/test_main.py
tests/unit/test_exceptions.py
tests/unit/test_file_checker.py

short circuit on ast error before tokenization error

---

.github/workflows/main.yml

This fixes installation on windows

Use python -mpip to install pip in github actions

---

src/flake8/processor.py

correct and deprecate the value of indent_size_str

---

docs/source/user/options.rst

Clarify where `--jobs` is disabled

---

docs/source/user/options.rst
src/flake8/formatting/_windows_color.py
src/flake8/formatting/base.py
src/flake8/formatting/default.py
src/flake8/main/options.py
src/flake8/plugins/manager.py
tests/unit/test_base_formatter.py
tests/unit/test_filenameonly_formatter.py
tests/unit/test_nothing_formatter.py
tox.ini

resolves #1379
here's what it looks like for example on ubuntu:

add --color option

---

docs/source/internal/utils.rst
src/flake8/defaults.py
src/flake8/options/manager.py
src/flake8/processor.py
src/flake8/utils.py
tests/unit/test_option.py
tests/unit/test_utils.py

detected using https://github.com/asottile/dead

remove dead code

---

src/flake8/main/application.py
src/flake8/main/cli.py
tests/integration/test_main.py
tests/integration/test_plugins.py

cherry-picked to catch a mistake in my other branch

improve integration tests

---

setup.cfg
src/flake8/checker.py
src/flake8/main/application.py
src/flake8/main/options.py
src/flake8/plugins/pyflakes.py
tests/fixtures/config_files/local-plugin.ini
tests/unit/test_get_local_plugins.py
tests/unit/test_pyflakes_codes.py

broken out from my other branch.  I added a TODO here but I've already completed it on another branch

move from allowlist to blocklist for mypy

---

src/flake8/api/legacy.py
src/flake8/main/application.py
src/flake8/main/options.py
src/flake8/options/manager.py
src/flake8/plugins/finder.py
src/flake8/style_guide.py
tests/integration/test_checker.py
tests/integration/test_plugins.py
tests/unit/plugins/finder_test.py
tests/unit/test_debug.py
tests/unit/test_decision_engine.py
tests/unit/test_legacy_api.py

this is the first step towards adding `--require-extension` / `--disable-extension`

move managing of off_by_default / enable_extensions to plugin loading

---

src/flake8/options/manager.py
src/flake8/plugins/finder.py
tests/integration/test_plugins.py
tests/unit/plugins/finder_test.py

accidentally regressed in #1504

fix extended_default_select from plugin loading

---

src/flake8/utils.py
tests/unit/test_utils.py

caused some confusion here: https://github.com/PyCQA/flake8/issues/1494#issuecomment-997437857

perform path normalization on '.'

---

src/flake8/api/legacy.py

though I plan to delete this, I figured I'd type it in the meantime in case I don't get around to a new api by the next release

type api.legacy.Report

---

setup.cfg
src/flake8/api/legacy.py
tests/unit/test_legacy_api.py

split into two commits
by typing I noticed a few things were recently broken in the legacy api so I fixed them

type the rest of the legacy api

---

.github/ISSUE_TEMPLATE/02_feature.yml

- revert link back to the top level header
- add notices about not implementing any checks

update feature issue form

---

src/flake8/options/config.py
tests/unit/test_options_config.py

always use UTF-8 encoding when reading configuration

---

docs/source/user/options.rst
src/flake8/api/legacy.py
src/flake8/main/application.py
src/flake8/main/options.py
src/flake8/plugins/finder.py
src/flake8/utils.py
tests/integration/test_plugins.py
tests/unit/plugins/finder_test.py
tests/unit/test_legacy_api.py
tests/unit/test_utils.py

add a --require-plugins option

---

src/flake8/checker.py
src/flake8/processor.py
tests/integration/test_plugins.py
tests/unit/test_file_processor.py

use the actual line contents when processing physical lines

---

src/flake8/checker.py
src/flake8/processor.py
tests/unit/test_file_processor.py

previously this was mutating the argument and returning it -- now it doesn't mutate the argument and returns a new value

change keyword_arguments_for so it does not modify and return

---

src/flake8/checker.py
src/flake8/exceptions.py
tests/unit/test_exceptions.py
tests/unit/test_file_checker.py

include the file path in the plugin execution error

---

src/flake8/plugins/finder.py
tests/unit/plugins/finder_test.py

accidentally regressed in #1545

re-show pycodestyle in help after plugin gen

---

.pre-commit-config.yaml

(this makes my text editor happier, and also makes the errors more likely to point at the correct line on the first pass)

reorder configuration to put formatters first

---

src/flake8/plugins/finder.py
tests/unit/plugins/finder_test.py

this should make it error earlier on rather than slipping through and not being filterable later (especially with `per-file-ignores`)

forbid invalid plugin prefixes in plugin loading

---

docs/source/user/options.rst

https://github.com/PyCQA/pycodestyle/issues/1064

correct string example for E501 exclusions

---

src/flake8/style_guide.py
tests/unit/test_decision_engine.py

see https://github.com/PyCQA/flake8/issues/284#issuecomment-1165962426

don't consider default codes as explicitly selected unless listed

---

README.rst

Signed-off-by: Stavros Ntentos <133706+stdedos@users.noreply.github.com>

Add Discord invite badge to README.rst

---

src/flake8/checker.py
src/flake8/main/application.py

First contribution must be a typo fix!

Fix a typo

---

src/flake8/_compat.py

3.8.0 is ancient but might as well make it work
resolves #1637
tested manually in docker

work around un-pickleabiliy of EntryPoint in 3.8.0

---

setup.cfg

require sufficiently new importlib-metadata

---

docs/source/plugin-development/registering-plugins.rst
docs/source/user/options.rst

Add a short section to the plugin development.
See #1676

Document off-by-default feature

---

src/flake8/api/legacy.py
src/flake8/checker.py
src/flake8/main/application.py
src/flake8/options/parse_args.py
tests/integration/test_checker.py
tests/unit/test_checker_manager.py
tests/unit/test_legacy_api.py

I haven't actually tried this on windows or macos yet, but in theory it works
it also makes flake8 5-7% faster on `fork` platforms as well

enable multiprocessing on other platforms

---

src/flake8/checker.py
tests/integration/test_main.py

ensure results are sorted for file traversal

---

MANIFEST.in

packagers: please package from the github tgz
this has been broken for a while, I have no intention of supporting it and we don't test it

remove MANIFEST.in

---

src/flake8/plugins/pyflakes.py

deprecate --include-in-doctest --exclude-from-doctest

---

.github/FUNDING.yml

oops, bad copypasta. also not sure why the other one is 404

correct tidelift link

---

src/flake8/defaults.py

remove regex link

---

docs/source/user/options.rst
src/flake8/plugins/pyflakes.py

remove --include-in-doctest and --exclude-in-doctest

---

tests/unit/test_checker_manager.py

noticed while implementing the --jobs limiter

remove a few unnecessary mocks in test_checker_manager

---

src/flake8/checker.py

the original code was only passing pyflakes by accident due to `__future__.annotations`

adjust global variable definition for new pyflakes
